Added the task property window in a new PR to remove the build files …
scalability-llnl/ravel pull request #14
Opened 2018-06-12 15:26 UTC by viraj96

I am submitting a fresh PR and have removed the Ravel.pro.user file and the previous commits as well.

2018-06-13 18:09 UTC, kisaacs commented
Per Slack conversation, please update this so that task selection and timeline panning still behave as they did previously. Thanks!

2018-06-13 21:25 UTC, kisaacs commented on src/mainwindow.h
> +#include "traditionalvis.h"
Where is this used?

2018-06-13 21:28 UTC, viraj96 commented on src/mainwindow.h
> +#include "traditionalvis.h"
Removed

2018-06-19 02:34 UTC, kisaacs requested changes

2018-06-19 02:34 UTC, kisaacs commented on src/mainwindow.h
> +class TraditionalVis;
Where is this used?

2018-06-19 02:34 UTC, kisaacs commented on src/timelinevis.cpp
> +        if( Qt::ControlModifier && event->modifiers() )
The spacing of this line doesn't match the others.

2018-06-19 02:34 UTC, kisaacs commented on src/timelinevis.h
> +    virtual void rightClickEvent(QMouseEvent * event){ Q_UNUSED(event); }
The spacing of this line doesn't match the others.

2018-06-19 02:34 UTC, kisaacs commented on src/traditionalvis.cpp
> +
Please fix the spacing throughout so it matches the rest of the project.

2018-06-19 02:34 UTC, kisaacs commented on src/mainwindow.cpp
> +}
Please fix spacing to match the rest of the project.

2018-06-22 16:54 UTC, kisaacs approved these changes

2018-06-22 16:55 UTC, merged